### ISSUE TITLE
Single LED and count on main board test

### ISSUE THREAD

**Issue by johnddias** [spenceraxani/CosmicWatch-Desktop-Muon-Detector#6]
Looking for any tips, please.  The main PCB is assembled and when I plug it in I see the LED blink once and the screen reports one measurement.  from the instructions I was expecting a solid LED and a negative count with the SPiM disconnected, what could be wrong?  Thanks

**Comment by spenceraxani** [comment]
Hi,

Not to worry, it’s probably fine. As long as you see that the CosmicWatch splash screen appears on the OLED and that you are seeing roughly +29.5V on the HV to GND pins on the 6-pin header , that’s about as much as you can test until you plug the SiPM in. 

An older version of the code wasn’t taking the dead time into account properly, and that is what was causing the negative count rate. This has been fixed with the updated Arduino code. 

Thanks,

Spencer

**Comment by johnddias** [comment]
Thanks Spencer.  I did get my SiPM ready and plugged in but getting the same result on the display.  I'm waiting for a scope to test things out before I give up hope.
